name: Trigger Pipeline Repo

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pipeline repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.YOUR_GH_PAT}}" \
            https://api.github.com/repos/yazicigurkan/petclinic-devops/dispatches \
            -d '{"event_type":"petclinic-updated"}'
